version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: Asia/Shanghai
    #user: 999:999
    volumes:
         - ./data:/usr/data
         #- ./data:/var/lib/mysql
         - ./conf.d:/etc/mysql
